os: linux
dist: bionic

sudo: required
language: rust
rust:
  - stable


cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xvfb
    - libx11-dev
    - libxkbfile-dev
    - libsecret-1-dev
    - libfontconfig-dev
    # Build RPM on Ubuntu
    - rpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi

script:
  - ./build_deb_pack.sh

deploy:
  release: sshimas-v0.1
  provider: releases
  api_key: $oath
  file: sshimas_0.1.0_amd64.deb
  skip_cleanup: true
  prerelease: true
  on:
    branch: master

notifications:
    email: false