os: Visual Studio 2015

skip_tags: true

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script: 
  - cargo build --release

artifacts:
- path: target\release\sshimas.exe
  name: sshimas

deploy:
  release: sshimas-v0.1.0
  description: 'Automatic release by appveyor'
  provider: GitHub
  auth_token:
    secure: nuSGI1gaApM0IIUBX0eIQ/6wWj55cNEQIqAH4HmiNLjoRdKMwYHw+bPoUMuwFyxz
  draft: false
  prerelease: true
  on:
    branch: master

