[package]
name = "sshimas"
version = "0.1.0"
authors = ["klaus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.25.0"
clap = "2.33.0"