[package]
name = "action"
version = "0.1.0"
authors = ["Klaus Klein <klauswk1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package = "common", path = "../common" }
